### PR TITLE
Bugfix/expanded border zero

### LINKED ISSUE #152: expandShorthand: true. I get an error, when shorthand property has a value unrelated to primary option.
Hello!

I created repo for reproduction. Please, check it:
https://github.com/nmatushevskiy/stylelint-declaration-strict-value-expandShorthand-issue

I want that in properties containing color the value to be as variable (like background-color, color, background, border etc).

To reach this, I use `stylelint-declaration-strict-value` plugin with `expandShorthand` property (see [stylelintrc.json](https://github.com/nmatushevskiy/stylelint-declaration-strict-value-expandShorthand-issue/blob/master/example.less) from repo for details).

I get an error, when in shorthand property has a value unrelated to color.

For example:

```
.example {
    border: 0; // unexpected error
}
```

see [example.less](https://github.com/nmatushevskiy/stylelint-declaration-strict-value-expandShorthand-issue/blob/master/example.less) from repo for details.

Is this expected behavior?

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #152

### CODE REVIEW

File: test/shorthand.js [hunk 1]
```diff
@@ -184,9 +184,9 @@ testRule(rule, {
     { code: '.foo { scrollbar-color: transparent darken(#fff, 10%); }' },
     { code: '.foo { scrollbar-color: darken(#fff, 10%) darken(#fff, 10%); }' },
     { code: '.foo { scrollbar-color: darken(#fff, 10%) transparent; }' },
-    { code: '.foo { boder: 0; }' },
-    { code: '.foo { boder: transparent; }' },
-    { code: '.foo { boder: 1px solid transparent; }' },
+    { code: '.foo { border: 0; }' },
```
Comment (AndyOGo) [inline test/shorthand.js:187]: @nmatushevskiy 
I have a test case here for your `border: 0` example.

File: test/shorthand.js [hunk 2]
```diff
@@ -184,10 +185,11 @@ testRule(rule, {
...
+    { code: '.foo { border: transparent; }' },
+    { code: '.foo { border: 1px solid transparent; }' },
     { code: '.foo { background: transparent; }' },
+    { code: '.foo { background: no-repeat; }' },
```
Comment (AndyOGo) [inline test/shorthand.js:192]: @nmatushevskiy
I have also added `background: no-repeat;` assertions.
